apiVersion: v1
kind: Pod
metadata:
  name: shell-privileged
spec:
  securityContext:
    runAsUser: 0
  containers:
  - name: shell
    image: registry.access.redhat.com/ubi9/ubi-minimal
    command: ["/bin/sleep", "infinity"]
    imagePullPolicy: Always
    resources:
      requests:
        memory: 64Mi
        cpu: 250m
      limits:
        memory: 128Mi
        cpu: 500m
